version: '3.9'

services:
  web:
    build: .
    container_name: task_api_web
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    dns:
      - 8.8.8.8
      - 8.8.4.4
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: postgres:15
    container_name: task_api_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tasks_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: task_api_redis
    ports:
      - "6379:6379"

  worker:
    build: .
    container_name: task_api_worker
    dns:
      - 8.8.8.8
      - 8.8.4.4
    command: celery -A app.celery_worker worker --loglevel=info
    depends_on:
      - redis
      - db
    env_file:
      - .env

  beat:
    build: .
    container_name: task_api_beat
    dns:
      - 8.8.8.8
      - 8.8.4.4
    command: celery -A app.celery_worker beat --loglevel=info
    depends_on:
      - redis
      - db
    env_file:
      - .env

volumes:
  postgres_data:
